import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ReportSchema } from "@/lib/pipeline/schemas";
import { reportToMarkdown } from "@/lib/report-markdown";

// content/sample-report.json is a real report, generated by scanning a real site, and shown at /sample.
// It is what a visitor sees when the daily limit is reached, as RepoRecon falls back to a cached result.
// This test keeps it from going stale (it must still match the report schema) or from carrying a secret.

const file = join(process.cwd(), "content", "sample-report.json");
const raw = readFileSync(file, "utf-8");

describe("content/sample-report.json", () => {
  it("is a valid, complete report", () => {
    const report = ReportSchema.parse(JSON.parse(raw));
    expect(report.overallScore).not.toBeNull();
    expect(report.modules.length).toBeGreaterThanOrEqual(4);
    expect(report.topFixes.length).toBeGreaterThan(0);
    expect(report.fixPrompt.length).toBeGreaterThan(100);
    expect(Number.isNaN(Date.parse(report.createdAt))).toBe(false);
  });

  it("shows the parts that need the optional services, so the sample is a fair picture of a full scan", () => {
    const report = ReportSchema.parse(JSON.parse(raw));
    expect(report.social).not.toBeNull();
    expect(report.competitors).not.toBeNull();
    expect(report.ideas.length).toBeGreaterThan(0);
    expect(report.modules.find((m) => m.module === "performance")?.score).not.toBeNull();
  });

  it("includes the executive summary, a roadmap that covers every finding, and a fix kit", () => {
    const report = ReportSchema.parse(JSON.parse(raw));
    expect(report.summary?.grade).not.toBeNull();
    const ids = report.modules.flatMap((m) => m.findings.map((f) => f.id)).sort();
    const planned = [...report.summary!.roadmap.thisWeek, ...report.summary!.roadmap.thisMonth, ...report.summary!.roadmap.thisQuarter].sort();
    expect(planned).toEqual(ids);
    expect(report.fixKit.length).toBeGreaterThan(0);
  });

  it("carries no key, token or secret", () => {
    for (const pattern of [/nvapi-[A-Za-z0-9_-]{10,}/, /AIza[A-Za-z0-9_-]{20,}/, /tvly-/, /FETCH_SERVICE_SECRET/, /local-test-secret/, /Bearer\s+\S{10,}/i, /sk-[A-Za-z0-9]{20,}/]) {
      expect(raw, String(pattern)).not.toMatch(pattern);
    }
  });

  it("exports to Markdown without trouble", () => {
    expect(reportToMarkdown(ReportSchema.parse(JSON.parse(raw)))).toContain("# SiteRecon report");
  });
});
